# Preprocessing, modeling and fine-tuning

We want to be able to predict churning.

Ideas for models:

1. start only with non-spatial features
2. if necessary, incorporate location

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
import pathlib
from sklearn.model_selection import train_test_split
import nmmn.misc

## Import dataset

### Read files

Plans, dependents, charges

In [3]:
plans=pd.read_excel(pathlib.Path('../data/services.xlsx'))

Churn reason, category and satisfaction score

In [4]:
status=pd.read_excel(pathlib.Path('../data/churn_status.xlsx'))

Location

In [5]:
loc=pd.read_excel(pathlib.Path('../data/location.xlsx'))

### Join

Join all tables into one for convenience

In [6]:
tmp = pd.merge(plans, status, on='Customer ID', how='inner')  # 'inner' join by default
df = pd.merge(tmp, loc, on='Customer ID', how='inner')

## 4. Prepare the data

When deploying this model for learning purposes, I learned an important lesson: 

> One should only keep the "production features" during training.

The issue I had was that when deploying with FastAPI, the model needed all 50 features when in fact it was only trained with less than 10. Keeping only the important features for training is called "train-with-only-what-you-serve".

### Train/validation split

In [7]:
train, val = train_test_split(df, test_size=0.2, random_state=42)

### Split features and labels

"Production feature list"

In [77]:
kept_cols=['Phone Service', 'Online Security', 'Online Backup', 'Premium Tech Support', 'Contract', 
           'Number of Referrals', 'Tenure in Months', 'Monthly Charge']

Let's separate the labels from the features: `X`=features, `Y`=labels.

In [78]:
labels=["Churn Value"]
X=train[kept_cols]
Xval=val[kept_cols]
Y=train[labels]
Yval=val[labels]

### Pipeline

The idea here in the spirit of scikit-learn is to create a pipeline that performs all necessary transformations on the raw data, be them log, ratios, etc etc. It will also include the standardization for ML training.

In [79]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder

In [83]:
# Features to keep
binary_categorical_features = ['Phone Service',	'Online Security', 'Online Backup',	'Premium Tech Support']  
multi_class_categorical_features = ['Contract'] 
numerical_features = ['Number of Referrals', 'Tenure in Months', 'Monthly Charge']

# Define preprocessing steps
preprocess = ColumnTransformer([
    ('binary_cat', OneHotEncoder(drop='if_binary'), binary_categorical_features),  # Binary encoded
    ('multi_cat', OneHotEncoder(), multi_class_categorical_features),  # One-hot encoding for multi-class
    ('num', StandardScaler(), numerical_features)  # Scaling for numerical features
], remainder='drop')

Inspect to see what came out

In [84]:
preprocess

ColumnTransformer(transformers=[('binary_cat', OneHotEncoder(drop='if_binary'),
                                 ['Phone Service', 'Online Security',
                                  'Online Backup', 'Premium Tech Support']),
                                ('multi_cat', OneHotEncoder(), ['Contract']),
                                ('num', StandardScaler(),
                                 ['Number of Referrals', 'Tenure in Months',
                                  'Monthly Charge'])])

In [85]:
temp=preprocess.fit_transform(X)

In [86]:
preprocess.get_feature_names_out()

array(['binary_cat__Phone Service_Yes', 'binary_cat__Online Security_Yes',
       'binary_cat__Online Backup_Yes',
       'binary_cat__Premium Tech Support_Yes',
       'multi_cat__Contract_Month-to-Month',
       'multi_cat__Contract_One Year', 'multi_cat__Contract_Two Year',
       'num__Number of Referrals', 'num__Tenure in Months',
       'num__Monthly Charge'], dtype=object)

# 5. Select and train model

In [87]:
import nmmn.ml

### a. Logistic regression

In [88]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

Incorporates model into pipeline

In [89]:
logistic = make_pipeline(preprocess, LogisticRegression(solver='lbfgs') )

Train the model

In [90]:
%%time
logistic.fit(X, Y)

CPU times: user 212 ms, sys: 35.7 ms, total: 248 ms
Wall time: 56.2 ms

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('binary_cat',
                                                  OneHotEncoder(drop='if_binary'),
                                                  ['Phone Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Premium Tech Support']),
                                                 ('multi_cat', OneHotEncoder(),
                                                  ['Contract']),
                                                 ('num', StandardScaler(),
                                                  ['Number of Referrals',
                                                   'Tenure in Months',
                                                   'Monthly Charge'])])),
                ('logisticregression', LogisticRegression())])

#### Accuracy

Training error

In [91]:
from sklearn.metrics import accuracy_score

In [92]:
accuracy_score(Y, logistic.predict(X))

0.820021299254526

Validation error

In [93]:
accuracy_score(Yval, logistic.predict(Xval))

0.8147622427253371

#### Coefficients

Inspect coefficients of logistic regression to understand what are the most important factors driving churn.

In [94]:
# Access the LogisticRegression model and feature names from the pipeline
logistic_model = logistic.named_steps['logisticregression']
feature_names = logistic.named_steps['columntransformer'].get_feature_names_out() # Assuming you have a ColumnTransformer

# Get the coefficients
coefficients = logistic_model.coef_[0]  # Access the first row (for binary classification)

# Create a DataFrame for better visualization
coef_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})

# Print the DataFrame
coef_df.sort_values(by='Coefficient', ascending=False, key=abs)

                                Feature  Coefficient
6          multi_cat__Contract_Two Year    -1.353316
0         binary_cat__Phone Service_Yes    -1.185605
9                   num__Monthly Charge     1.164548
4    multi_cat__Contract_Month-to-Month     1.025855
7              num__Number of Referrals    -0.811669
3  binary_cat__Premium Tech Support_Yes    -0.571248
8                 num__Tenure in Months    -0.569405
1       binary_cat__Online Security_Yes    -0.564855
2         binary_cat__Online Backup_Yes    -0.277128
5          multi_cat__Contract_One Year    -0.189942

### b. Random forest

In [95]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

In [96]:
forest = make_pipeline(preprocess, RandomForestClassifier(random_state=42))

Convert `Y` to one column for fitting

In [97]:
Ytrain1=np.argmax(Y.values, axis=1)
Yval1=np.argmax(Yval.values, axis=1)

In [98]:
%%time
# Train the classifier
forest.fit(X, Ytrain1)

CPU times: user 99.8 ms, sys: 4.93 ms, total: 105 ms
Wall time: 108 ms

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('binary_cat',
                                                  OneHotEncoder(drop='if_binary'),
                                                  ['Phone Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Premium Tech Support']),
                                                 ('multi_cat', OneHotEncoder(),
                                                  ['Contract']),
                                                 ('num', StandardScaler(),
                                                  ['Number of Referrals',
                                                   'Tenure in Months',
                                                   'Monthly Charge'])])),
                ('randomforestclassifier',
                 RandomForestClassifier(random_state=42))])

#### Accuracy

Training error

In [99]:
accuracy_score(Y, forest.predict(X))

0.7392616258430955

Validation error

In [100]:
accuracy_score(Yval, forest.predict(Xval))

0.71611071682044

### c. XGBoost

In [101]:
from xgboost import XGBClassifier

In [102]:
# Set up the parameters for the XGBoost model
params = {
    'objective': 'binary:logistic',  
    'max_depth': 6,                # Depth of the trees
    'learning_rate': 0.1,          # Step size shrinkage
    'eval_metric': 'logloss',     
    'seed': 42                     # For reproducibility
}

#### Train

In [103]:
gbm = make_pipeline(preprocess, XGBClassifier(**params))#, use_label_encoder=False))

In [104]:
%%time
# Train the classifier
gbm.fit(X, Y)

CPU times: user 172 ms, sys: 33.4 ms, total: 206 ms
Wall time: 77.5 ms

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('binary_cat',
                                                  OneHotEncoder(drop='if_binary'),
                                                  ['Phone Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Premium Tech Support']),
                                                 ('multi_cat', OneHotEncoder(),
                                                  ['Contract']),
                                                 ('num', StandardScaler(),
                                                  ['Number of Referrals',
                                                   'Tenure in Months',
                                                   'Monthly Charge'])])),
                ('xgbclassifier',
                 XGBClassifier(base_sc...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

#### Accuracy

Training error

In [105]:
accuracy_score(Y, gbm.predict(X))

0.8718494852680156

Validation error

In [106]:
accuracy_score(Yval, gbm.predict(Xval))

0.829666430092264

### Model comparison

#### Accuracy (%)

| Model    | Training | Validation | 
|----------|----------|------------|
| Random   | 50       |            | 
| Logistic | 82       | 81         | 
| RF       | 74       | 72         | 
| GBM      | 87       | 83         |

## 6. Fine-tune

We selected *XGBoost* as the best model. Let's pick the best hyperparameters in a Monte Carlo fashion.

In [109]:
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV
from sklearn.model_selection import RandomizedSearchCV
import scipy.stats
from sklearn.pipeline import Pipeline

### Hyperparameters

In [122]:
params = {
    "objective":        "binary:logistic",   # or “multi:softprob”
    "eval_metric":      "logloss",
    "n_jobs":           8,
    "random_state":     42,
}

In [123]:
tuningPipeline = Pipeline([
    ("preprocess", preprocess),
    ("xgb", XGBClassifier(**params)),
])

In [124]:
param_distribs = {
    # number of trees
    "xgb__n_estimators":     scipy.stats.randint(100, 1000),
    # step size shrinkage
    "xgb__learning_rate":    scipy.stats.loguniform(1e-3, 1.0),
    # tree depth
    "xgb__max_depth":        scipy.stats.randint(3, 12),
    # minimum sum hessian in leaf
    "xgb__min_child_weight": scipy.stats.randint(1, 10),
    # subsample rows & features
    "xgb__subsample":        scipy.stats.uniform(0.5, 0.5),
    "xgb__colsample_bytree": scipy.stats.uniform(0.5, 0.5),
    # complexity control
    "xgb__gamma":            scipy.stats.loguniform(1e-8, 5.0),
    # L1/L2 regularization
    "xgb__reg_alpha":        scipy.stats.loguniform(1e-8, 1.0),
    "xgb__reg_lambda":       scipy.stats.loguniform(1e-8, 10.0),
}

### Number crunching

Let's try 100 random combinations of hyperparameters: `niter * cv`

In [125]:
niter=10
cv=10

In [126]:
search = RandomizedSearchCV(
    tuningPipeline, param_distributions=param_distribs, n_iter=niter, cv=cv,
    scoring='accuracy', random_state=42)

In [127]:
import warnings
warnings.filterwarnings("ignore", module="sklearn.*") # Suppress warnings from the sklearn module

In [128]:
%%time
search.fit(X, Y)

CPU times: user 35.6 s, sys: 1.02 s, total: 36.6 s
Wall time: 9.21 s

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('preprocess',
                                              ColumnTransformer(transformers=[('binary_cat',
                                                                               OneHotEncoder(drop='if_binary'),
                                                                               ['Phone '
                                                                                'Service',
                                                                                'Online '
                                                                                'Security',
                                                                                'Online '
                                                                                'Backup',
                                                                                'Premium '
                                                                                'Tech '
                                                                                'Support']),
                                                                              ('multi_cat',
                                                                               OneHotEncoder(),
                                                                               ['Contract']),
                                                                              ('num',
                                                                               StandardScaler(),
                                                                               ['Number '
                                                                                'of '
                                                                                'Referrals',
                                                                                'Tenure '
                                                                                'in '
                                                                                'Months',
                                                                                'Monthly '
                                                                                'Cha...
                                        'xgb__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x13be20150>,
                                        'xgb__reg_alpha': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x15dc54e10>,
                                        'xgb__reg_lambda': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x15dc56a90>,
                                        'xgb__subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x15d5a2990>},
                   random_state=42, scoring='accuracy')

In [129]:
res = pd.DataFrame(search.cv_results_)
res.sort_values(by="mean_test_score", ascending=False, inplace=True)
res.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_xgb__colsample_bytree,param_xgb__gamma,param_xgb__learning_rate,param_xgb__max_depth,param_xgb__min_child_weight,param_xgb__n_estimators,...,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.031100,0.008037,0.004018,0.000498,0.687270,1.863096e+00,0.157030,7,7,221,...,0.833333,0.834813,0.820604,0.817052,0.822380,0.829485,0.836590,0.826589,0.009317,1
7,0.060349,0.000609,0.003718,0.000342,0.760417,2.297241e+00,0.341666,4,5,891,...,0.829787,0.836590,0.808171,0.818828,0.836590,0.824156,0.833037,0.825170,0.011517,2
9,0.032161,0.000604,0.003708,0.000073,0.599421,1.541496e-02,0.234707,7,7,140,...,0.831560,0.824156,0.804618,0.804618,0.813499,0.833037,0.829485,0.819665,0.010045,3
3,0.054754,0.001100,0.004071,0.000139,0.683181,9.275538e-05,0.226740,5,7,343,...,0.819149,0.829485,0.793961,0.801066,0.817052,0.822380,0.825933,0.814342,0.010530,4
4,0.068582,0.015085,0.004276,0.000276,0.585262,3.680288e-08,0.702517,4,9,445,...,0.822695,0.827709,0.783304,0.792185,0.806394,0.817052,0.804618,0.805644,0.014387,5

### Results

Best hyperparameters

In [132]:
cols=[6,7,8,24]
res2=res.iloc[:, cols]
res2.head()

,param_xgb__learning_rate,param_xgb__max_depth,param_xgb__min_child_weight,mean_test_score
0,0.157030,7,7,0.826589
7,0.341666,4,5,0.825170
9,0.234707,7,7,0.819665
3,0.226740,5,7,0.814342
4,0.702517,4,9,0.805644

There is very little room for tuning, so I will not bother.

finalModel = search.best_estimator_  # includes preprocessing

accuracy_score(YtestG, finalModel.predict(Xtest))

## 7. Present solution

Saves model for deployment

In [133]:
import joblib

In [134]:
joblib.dump(gbm, "../data/best_model.joblib", compress=3)

['../data/best_model.joblib']

## Sandbox

Inspect features for Pydantic

In [52]:
X.shape

(5634, 50)